In [1]:
import cv2
import numpy as np

In [4]:
a = np.array([
    [1, 2, 1, 4, 5],
    [2, 1, 3, 4, 2],
    [3, 2, 5, 1, 2],
    [5, 2, 1, 1, 4],
    [6, 3, 3, 2, 5]
], np.uint8)
kernel = np.array([
    [0, 1, 0],
    [1, -4, 1],
    [0, 1, 0]
])

print(np.shape(a))
print(np.shape(kernel))

dst = cv2.filter2D(a, -1, kernel)
print(dst)

(5, 5)
(3, 3)
[[4 0 8 0 0]
 [0 5 0 0 7]
 [0 3 0 8 0]
 [0 3 7 4 0]
 [0 1 0 2 0]]


In [21]:
img = np.array([
    [0, 0, 0, 1, 1, 0, 0],
    [0, 0, 1, 1, 0, 0, 0],
    [0, 0, 1, 1, 1, 1, 0],
    [0, 1, 1, 0, 1, 1, 0],
    [0, 1, 0, 1, 1, 1, 0],
    [0, 1, 1, 1, 1, 1, 0],
    [0, 0, 0, 1, 1, 0, 0],
], np.uint8)
kernel = np.array([1, 1, 1], np.uint8)

erosion = cv2.erode(img, kernel, anchor=(0, 0), iterations=1)
print(erosion)

[[0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 1 1 0]
 [0 1 0 0 1 1 0]
 [0 0 0 1 1 0 0]
 [0 0 0 1 1 0 0]
 [0 0 0 1 1 0 0]]
