# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt


In [2]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [3]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [4]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [5]:
img

array([[1, 8, 3, 4, 5, 4, 7, 7, 8, 8, 8, 4],
       [2, 4, 3, 5, 8, 4, 3, 5, 4, 0, 6, 9],
       [2, 9, 7, 4, 6, 9, 1, 7, 7, 4, 2, 7],
       [3, 8, 6, 7, 3, 8, 4, 8, 9, 9, 5, 4],
       [1, 5, 6, 4, 8, 6, 0, 2, 5, 3, 9, 1],
       [0, 5, 7, 1, 9, 5, 9, 4, 0, 4, 0, 1],
       [8, 0, 1, 4, 8, 2, 7, 7, 7, 2, 3, 6],
       [3, 7, 8, 2, 9, 0, 3, 3, 7, 8, 3, 2],
       [3, 0, 7, 8, 9, 8, 2, 2, 8, 4, 0, 5],
       [3, 7, 8, 2, 1, 6, 1, 0, 5, 4, 6, 0],
       [1, 0, 4, 0, 6, 8, 5, 7, 1, 2, 4, 8],
       [4, 9, 0, 8, 5, 9, 8, 1, 2, 9, 2, 8]])

In [6]:
h,w=img.shape

In [7]:
print(h,w)

12 12


In [8]:
#[*range(-2,3)]

In [9]:
dst = np.zeros((h,w),np.int)

C:\Users\admin\AppData\Local\Temp/ipykernel_15684/2160328971.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dst = np.zeros((h,w),np.int)


In [10]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [11]:
img

array([[1, 8, 3, 4, 5, 4, 7, 7, 8, 8, 8, 4],
       [2, 4, 3, 5, 8, 4, 3, 5, 4, 0, 6, 9],
       [2, 9, 7, 4, 6, 9, 1, 7, 7, 4, 2, 7],
       [3, 8, 6, 7, 3, 8, 4, 8, 9, 9, 5, 4],
       [1, 5, 6, 4, 8, 6, 0, 2, 5, 3, 9, 1],
       [0, 5, 7, 1, 9, 5, 9, 4, 0, 4, 0, 1],
       [8, 0, 1, 4, 8, 2, 7, 7, 7, 2, 3, 6],
       [3, 7, 8, 2, 9, 0, 3, 3, 7, 8, 3, 2],
       [3, 0, 7, 8, 9, 8, 2, 2, 8, 4, 0, 5],
       [3, 7, 8, 2, 1, 6, 1, 0, 5, 4, 6, 0],
       [1, 0, 4, 0, 6, 8, 5, 7, 1, 2, 4, 8],
       [4, 9, 0, 8, 5, 9, 8, 1, 2, 9, 2, 8]])

In [12]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  -6,  -7,   1,  12,  -8,  -5,  -1,  -4, -22,   5,   0],
       [  0,  15,   6,  -9,   0,  17, -19,   7,   4,  -2, -14,   0],
       [  0,   9,  -4,  11, -17,  10,  -1,  10,   7,  15,  -4,   0],
       [  0,   0,   2,  -6,  10,   3, -21,  -9,   6, -15,  27,   0],
       [  0,   8,  15, -20,  14,  -6,  20,  -2, -20,  11, -17,   0],
       [  0, -21, -15,   4,   8, -12,   7,   7,  12, -14,   1,   0],
       [  0,  17,  15, -21,  17, -22,   0,  -7,   2,  16,  -1,   0],
       [  0, -24,   4,  12,  10,  15,  -6,  -5,  14,  -4, -18,   0],
       [  0,  17,  12,  -9, -19,   6,  -9, -15,   7,  -1,  16,   0],
       [  0, -21,   8, -20,  10,   6,  -4,  21, -12, -10,  -2,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [13]:
img = cv2.imread('../resource/img/lena.png', 0)

In [14]:
h,w=img.shape

In [15]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [16]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [17]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()